---
- name: install necessary php packages
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: true
  register: install_php_packages

- name: install apache
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  register: install_apache

- name: start apache
  systemd:
    name: apache2
    state: started
    enabled: true
