---
# handlers file for wordpress
#- name: start apache-httpd
#  service:
#    name: apache2
#    state: started
#    enabled: true

- name: restart apache-httpd
  systemd:
    name: apache2
    state: restarted
  register: restart_apache
