---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-test
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build: true
  #  - name: instance
  #    image: quay.io/centos/centos:stream8
  #    pre_build_image: true
provisioner:
  name: ansible
  #verifier:
  #  name: ansible
